export const searchData = [
	{
		data: {
			birthday: '12',
			birthdayMonth: 'once at 6 months',
			instagram: 'mauricio.id',
			name: 'Maurício',
			number: '21970135693',
			returningDate: '15',
			returningFrequence: 'maio',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'axFjq2EIGMltEGHSE9vo',
	},
	{
		data: {
			birthday: '15',
			birthdayMonth: 'once at three months',
			name: 'Lucas',
			number: '219474738',
			returningDate: '18',
			returningFrequence: '',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'b4drGgBovmv736mbKHRP',
	},
	{
		data: {
			birthday: '19',
			birthdayMonth: 'janeiro',
			instagram: 'gbrl.pimenta',
			name: 'Gabriel Pimenta',
			number: '21964811623',
			returningDate: '15',
			returningFrequence: 'julho',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'gqn0Rzj2Sg1WPsxls1W8',
	},

	{
		data: {
			birthday: '12',
			birthdayMonth: 'once at 6 months',
			instagram: 'mauricio.id',
			name: 'Maurício',
			number: '21970135693',
			returningDate: '15',
			returningFrequence: 'maio',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'axFjq2EIGMltEGHSE9vo',
	},
	{
		data: {
			birthday: '15',
			birthdayMonth: 'once at three months',
			name: 'Lucas',
			number: '219474738',
			returningDate: '18',
			returningFrequence: '',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'b4drGgBovmv736mbKHRP',
	},
	{
		data: {
			birthday: '19',
			birthdayMonth: 'janeiro',
			instagram: 'gbrl.pimenta',
			name: 'Gabriel Pimenta',
			number: '21964811623',
			returningDate: '15',
			returningFrequence: 'julho',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'gqn0Rzj2Sg1WPsxls1W8',
	},

	{
		data: {
			birthday: '12',
			birthdayMonth: 'once at 6 months',
			instagram: 'mauricio.id',
			name: 'Maurício',
			number: '21970135693',
			returningDate: '15',
			returningFrequence: 'maio',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'axFjq2EIGMltEGHSE9vo',
	},
	{
		data: {
			birthday: '15',
			birthdayMonth: 'once at three months',
			name: 'Lucas',
			number: '219474738',
			returningDate: '18',
			returningFrequence: '',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'b4drGgBovmv736mbKHRP',
	},
	{
		data: {
			birthday: '19',
			birthdayMonth: 'janeiro',
			instagram: 'gbrl.pimenta',
			name: 'Gabriel Pimenta',
			number: '21964811623',
			returningDate: '15',
			returningFrequence: 'julho',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'gqn0Rzj2Sg1WPsxls1W8',
	},

	{
		data: {
			birthday: '12',
			birthdayMonth: 'once at 6 months',
			instagram: 'mauricio.id',
			name: 'Maurício',
			number: '21970135693',
			returningDate: '15',
			returningFrequence: 'maio',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'axFjq2EIGMltEGHSE9vo',
	},
	{
		data: {
			birthday: '15',
			birthdayMonth: 'once at three months',
			name: 'Lucas',
			number: '219474738',
			returningDate: '18',
			returningFrequence: '',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'b4drGgBovmv736mbKHRP',
	},
	{
		data: {
			birthday: '19',
			birthdayMonth: 'janeiro',
			instagram: 'gbrl.pimenta',
			name: 'Gabriel Pimenta',
			number: '21964811623',
			returningDate: '15',
			returningFrequence: 'julho',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'gqn0Rzj2Sg1WPsxls1W8',
	},

	{
		data: {
			birthday: '12',
			birthdayMonth: 'once at 6 months',
			instagram: 'mauricio.id',
			name: 'Maurício',
			number: '21970135693',
			returningDate: '15',
			returningFrequence: 'maio',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'axFjq2EIGMltEGHSE9vo',
	},
	{
		data: {
			birthday: '15',
			birthdayMonth: 'once at three months',
			name: 'Lucas',
			number: '219474738',
			returningDate: '18',
			returningFrequence: '',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'b4drGgBovmv736mbKHRP',
	},
	{
		data: {
			birthday: '19',
			birthdayMonth: 'janeiro',
			instagram: 'gbrl.pimenta',
			name: 'Gabriel Pimenta',
			number: '21964811623',
			returningDate: '15',
			returningFrequence: 'julho',
			userUid: '9vmYJafy0rfw7VhmODzOpNFA9fu2',
		},
		id: 'gqn0Rzj2Sg1WPsxls1W8',
	},
];
